### ISSUE TITLE
Wallet isn't responding on the new MacOS 11.0.1 (BigSur) Update

### ISSUE THREAD

**Issue by Yummis** [VitaeTeam/Vitae#81] opened 2020-11-13 08:29 UTC
Hi developers!
Hurry up! seems like the QT Wallet is not compatible with the new MacOS update, you cannot leave us all in the dark!

**Comment by 2a5A1Ghu1** [comment] 2020-11-13 08:31
Curious as to what the error is that you are having?

**Comment by Yummis** [comment] 2020-11-13 08:32
All it says is "Application Not Responding" cannot be opened at all

**Comment by 2a5A1Ghu1** [comment] 2020-11-13 08:33
Debug log?

**Comment by Yummis** [comment] 2020-11-13 08:35
[debug.log](https://github.com/VitaeTeam/Vitae/files/5535628/debug.log)

**Comment by 2a5A1Ghu1** [comment] 2020-11-13 08:44
Looks like the backend is running fine, this may be an issue with how QT was built within gitian. Maybe a native build needs to be made. Currently I do not own a machine that can be updated to the latest OS(without some hackery) so I can not confirm this...

When I have a chance I will look into purchasing an ARM based mac and the last model(hopefully) of intel based mac to see what the issue is. I have already been saving up for this situation well in advance.

What processor are you running so I can start there first?

**Comment by Yummis** [comment] 2020-11-13 08:45
<img width="698" alt="image" src="https://user-images.githubusercontent.com/34694228/99047784-9a576500-258c-11eb-9829-069152437ad2.png">

**Comment by Willy7882** [comment] 2020-11-17 01:07
Ik heb hetzelfde probleem. Kan mijn macboock niet naar OS Sierra terugzetten, dus kan aan mijn coins niet aan !!
Erg vervelend ! Zolang dit niet opgelost is verliezen we mogelijk geld...

**Comment by Willy7882** [comment] 2020-11-17 01:09
> Het lijkt erop dat de backend goed werkt, dit kan een probleem zijn met hoe QT is gebouwd binnen gitian. Misschien moet er een native build worden gemaakt. Momenteel heb ik geen machine die kan worden geüpdatet naar het nieuwste besturingssysteem (zonder enige hackery), dus ik kan dit niet bevestigen ...
> 
> Als ik de kans krijg, zal ik kijken naar de aanschaf van een ARM-gebaseerde mac en het laatste model (hopelijk) van op Intel gebaseerde mac om te zien wat het probleem is. Ik heb al ruim van tevoren voor deze situatie gespaard.
> 
> Welke processor gebruik je zodat ik daar als eerste kan beginnen?

Processor : Dual-Core Intel Core i5

**Comment by Yummis** [comment] 2020-11-17 01:30
﻿
﻿
﻿
If you have a Time Machine Backup you can go back to previous OS version without loosing anything, if you don’t have a Backup you can still downgrade to previous OS but you will loose all your data, if you choose to do so, make sure you have a copy of your VITAE folder in Application Support

**Comment by Yummis** [comment] 2020-11-17 01:33
If you have a Time Machine Backup you can go back to previous OS version without loosing anything, if you don’t have a Backup you can still downgrade to previous OS but you will loose all your data, if you choose to do so, make sure you have a copy of your VITAE folder from Application Support
You can access the folder by going to Finder, “Go to Folder” ~/Library/Application Support

**Comment by 2a5A1Ghu1** [comment] 2020-11-17 04:15
I will be making a pull request for the fix shortly

**Comment by 2a5A1Ghu1** [comment] 2020-11-17 08:47
Here is the pull request you can compile it yourself or wait for a release with the fix.

https://github.com/VitaeTeam/Vitae/pull/82

**Comment by Yummis** [comment] 2020-12-02 23:41
When can we expect a new release with this issue fixed?

**Comment by fabioganga** [comment] 2020-12-10 13:59
I also vote for a new release to be issued, please. I am trying to compile it myself on my iMac but it throws errors, so I must be doing something wrong. Please, VITAE developers, come to our aid. Thanks.

**Comment by Yummis** [comment] 2020-12-14 02:34
I tried the last version (VITAE Core version v4.5.1-rc1-1-gb444abc-dirty (64-bit)) and it works perfectly on Mac OS BigSur

**Comment by Willy7882** [comment] 2021-03-06 17:18
Dear developers,
I can't download the wallet for Big Sur! The Vitae team told to download the new wallet, bu it does'nt work!
Can you please solve the problem?
Thankx

**Comment by 2a5A1Ghu1** [comment] 2021-03-11 21:51
Has been resolved with new release

**Closed by 2a5A1Ghu1** 2021-03-11 21:51 UTC
